name: Update README

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update README
        run: echo "Updating" >> filetoupdate.sh
      - name: Commit changes
        run: |
          git config --global user.name 'JeremyCrapon'
          git config --global user.email 'jeremy.crapon@gmail.com'
          git add filetoupdate.sh
          git commit -m "Auto update filetoupdate with date"
          git push
