name: Update README

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday
permissions:
  contents: write
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update README
        run: echo "Last update" >> README.md
      - name: Commit changes
        run: |
          git config --global user.name 'JeremyCrapon'
          git config --global user.email 'jeremy.crapon@gmail.com'
          git add README.md
          git commit -m "Auto update README with date"
          git push
