name: Update README

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Update README
        run: echo "Last update v3" >> README.md
      - name: Commit changes
        run: |
          git config --global user.email 'jeremy.crapon@gmail.com'
          git add README.md
          git commit -m "Auto update README with date"
          git push
